### ISSUE TITLE
RFC: Add docker support for kcptun

### ISSUE THREAD

**Issue by netroby** [xtaci/kcptun#172]
I am using docker to run kcptun server and client for myself. I would like to share my experience on docker containers.

Dockerfile  for server

``` dockerfile
FROM alpine
RUN apk update ; \
        apk add git go;\
        export GOPATH=/opt/go; \
        go get -u -v github.com/xtaci/kcptun/server; \
        mv /opt/go/bin/server /bin/server;\
        apk del openssl ca-certificates libssh2 curl expat pcre git go;\
        rm -rf /opt/go ;\
        rm -rf /usr/lib/go;

CMD ["server"]
```

Dockerfile for client

``` dockerfile
FROM alpine
RUN apk update ; \
        apk add git go;\
        export GOPATH=/opt/go; \
        go get -u -v github.com/xtaci/kcptun/client; \
        mv /opt/go/bin/client /bin/client;\
        apk del openssl ca-certificates libssh2 curl expat pcre git go;\
        rm -rf /opt/go ;\
        rm -rf /usr/lib/go;

CMD ["client"]
```

You can run server with docker very quickly

``` bash
docker run -d --restart=always --name kts -p 443:443 netroby/docker-kt-server server --key longs3cret  -l :443 -t upstream.proxy.server.ip:8123 -nocomp -crypt salsa20
```

The server side ,you need run your http proxy (like squid proxy server)

And run client with docker

``` bash
docker run -d --restart=always --name ktc -p 7878:7878 netroby/docker-kt-client client --key longs3cret --localaddr  :7878 --remoteaddr i.am.server.ip:443 --nocomp --crypt salsa20
```

I already build docker image on hub.docker.com

https://hub.docker.com/r/netroby/docker-kt-server/
https://hub.docker.com/r/netroby/docker-kt-client/

And here is my docker-compose.yml to deploy kcptun server

```
version: '2'
services:
  kts:
    image: netroby/docker-kt-server
    ports:
      - "443:443/udp"
    restart: always
    command: server -key longs3cret -l :443  -t gohttpproxy:8123 -nocomp -crypt salsa20
    depends_on:
      - gohttpproxy
    links:
      - gohttpproxy
  gohttpproxy:
    image: netroby/docker-gohttpproxy

```
